### ISSUE TITLE
Build Error: Could not find native static library 'c'

### ISSUE THREAD

**Issue by ashlin4010** [benbrittain/apache-nimble-sys#3]
Hi,

I have been trying to build the example trouble project that uses apache-nimble-sys. I was getting this error and wondered if you had any insight.

```
cargo build --target="thumbv7em-none-eabi"
...
Compiling embassy-nrf v0.2.0 (https://github.com/embassy-rs/embassy.git?rev=1cfd5370ac012814b7b386ba9ad8499529bdde4e#1cfd5370)
error: could not find native static library 'c', perhaps an -L flag is missing?
error: could not compile `apache-nimble` (lib) due to 1 previous error
```

Thanks

**Comment by Univa** [comment]
Sorry for the late reply. I'll need more information about your environment to help further, but make sure have `arm-none-eabi-gcc`/`arm-none-eabi-cc` installed, and that the `BINDGEN_EXTRA_CLANG_ARGS` environment variable points to the right sysroot path. Give the [build script](https://github.com/benbrittain/apache-nimble-sys/blob/3bb505944b4a030f67993671064c6c30288661e8/apache-nimble/build.rs#L73) a look as well, make sure your chip is supported (right now its just nRF52840) and that the `libc` path there exists on your system. If you have the arm compiler, then you can get the sysroot path with `arm-none-eabi-gcc -print-sysroot`

**Comment by ashlin4010** [comment]
Exploring other solutions. Closing issue.
